-- SQL Script to Create Missing Tables in Supabase
-- Copy and run this script in the Supabase SQL Editor (https://supabase.com -> Project -> SQL Editor)

-- 1. Create testimonials table
CREATE TABLE IF NOT EXISTS public.testimonials (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text NOT NULL,
  role text NOT NULL,
  avatar_url text,
  body text NOT NULL,
  rating integer NOT NULL DEFAULT 5
);

-- 2. Create resume table
CREATE TABLE IF NOT EXISTS public.resume (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  tab text NOT NULL,
  title text NOT NULL,
  role text,
  period text NOT NULL,
  description text
);

-- 3. Create about_me table
CREATE TABLE IF NOT EXISTS public.about_me (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  section text UNIQUE NOT NULL,
  title text NOT NULL,
  content text NOT NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resume ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.about_me ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS Policies for public access (Anon Key)
-- Testimonials Policies
CREATE POLICY "Allow public read access for testimonials" ON public.testimonials FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for testimonials" ON public.testimonials FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access for testimonials" ON public.testimonials FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access for testimonials" ON public.testimonials FOR DELETE USING (true);

-- Resume Policies
CREATE POLICY "Allow public read access for resume" ON public.resume FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for resume" ON public.resume FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access for resume" ON public.resume FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access for resume" ON public.resume FOR DELETE USING (true);

-- About Me Policies
CREATE POLICY "Allow public read access for about_me" ON public.about_me FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for about_me" ON public.about_me FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access for about_me" ON public.about_me FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access for about_me" ON public.about_me FOR DELETE USING (true);
